[package]
name = "groth16"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bellperson = "0.26.0"
blstrs = "0.7.1"
ff = "0.13.0"
pairing = "0.23.0"
rand = "0.8.5"
sha2 = "0.10.8"